name: Deploy R Program to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa 

        # Add EC2 public IP to known_hosts
        ssh-keyscan -H <EC2_PUBLIC_IP> | tee ~/.ssh/known_hosts

    - name: Copy R script to EC2
      run: |
        scp -o StrictHostKeyChecking=no simple_program.R ec2-user@<EC2_PUBLIC_IP>:~/simple_program.R

    - name: Execute R script on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@<EC2_PUBLIC_IP> "Rscript ~/simple_program.R"
