name: Deploy R Program to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-r-to-ec2:
    name: Deploy R Program to EC2 Instance
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure SSH Access
      env:
        EC2_IP: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        # Create .ssh directory and set permissions
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Add EC2 public IP to known_hosts
        ssh-keyscan -H 54.164.80.110 >> ~/.ssh/known_hosts

    - name: Copy R Script to EC2
      env:
        EC2_IP: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        scp app.r ec2-user@54.164.80.110:~/simple-r-app

    - name: Run R Script on EC2
      env:
        EC2_IP: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        ssh ec2-user@54.164.80.110: "Rscript ~/app.r"
