name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{secrets.MIIEpAIBAAKCAQEA/OVWq9L7uUe7M4WxH1J0/pxfCP7xILim5n7nLiZk3Ho/QMhzVeerAURtofGw/HRKL/2OSFgWUNRxuDZJg+FwyAGKZc+aU7UtPPENSs13wgCHLLFAk4c8Fs8xIDxHp4uzB6Bo+ySvOEYycWf5O6raWM5hPkAhG1V5okjEoHRiZE1lnNYcq4fieybJIKUA8YSKQPbTkBMxz7TkxfGSajCBz96hfTMPmK1RD2W4oX0AFkmMYzphGYV38MKRRN+mVTRrdpXYCxxJL1oxRYu/6KE4IoXXc46m5qwuJ4E7j2d+U7EXYROJ5ke+zBA0E2P27tSox4U6DJLiYNevavgus3Ka/QIDAQABAoIBADpqNwTlbSO0//a8sNcNUtzk/ca0LLpkLJkdQwUT9URAMJAkPQ/gvU1Doxc/HqSRr/k51j27qxvsln/4ei6uSkDIqlEuDPW86cAj5fAbWchEGvUl1Ea/fA/AuBY8FkkLKcVfNiCcrqSPAmPTomw34MuWkDuy0HLh4YCs0k5F09xa1svqqM3TzfaIKtYW8GCoHSnI7wgFpVjGwoQ3V8fQJ6iNZn/nXN0UCUIQxtFttp3AOBWZlKO6IAX88BdUkoM2x9QjST3J4QtxxRoj2SQzD9EKrKnRo9BMQMz/ktSDWcbG37JGQm6cWAxED8mwdXzTqRRNysfYrWrjmM8Ru48DlzkCgYEA/os8pMoRvdzecJiKv0qtWI8WMNuC/291ztqmi2W18B9feJbFvo216SGLYhTH4iuixR66uvAfg8woxyWWbt14tPoo4FfoljnO+T0yIEUUsOL+u7L9sH02wYg0fv3pQNuptwCkhrJJPNSeBR6yhpNsra3M7P8kInCatemcBOf/v8sCgYEA/lewL0GbjcyvNbDCt364HVXp0kbmfOEKGSZIBG1uGP/+psxI6TOJrmEES+RmPih/g32ylMnwbQWAfT1pC8XognO26dCTEECMMMMq7WUta4vJ2DN0fZD+5JF+dUUNTZDpMvfJ4Xe6EwUBwfOBUuj3Y3FFUjMV+qCR35YVdtzhp1cCgYEAhxqeQJUkX5L42eiNVEUtxuCDlcEdQbkGXZm+ZiTBMcdlJBtar+6FjE0Kry96fHhOt7O8xvYmtAzL5A/2Tbftlplk0ta2E+5xBedOUMR52/1P2Y6CioebZZOG0ZSxloRBC2oi6X990fTEPtFxTm63c2PZbj1qD4GXDFEHR69gFosCgYACXgqTxgaOoVMYKtcFIjbQfxY4ENTgYK/ZYBPXhrU5olhacRhUo1gquVhy5GNXPMVDEg5xeBe2zBBQGhw6MdNiM3WGY5ya0B797TMfFov/rkNoscHp0UmuEvScXtIq4KhrAwdsA9NFjgxgI8YWYXi8Ajfk9fjEZm41KI52lsO67QKBgQCpwkaF4tNB6fPkaVQuIVKZs4APo7eaJIsXue5MntU2rvDmiTXdG1tASBfy8EeL32/HvqnyzkDQUzedcG1aSRdc50oeffWl35guBU8Qhp+fWY+nRxpYg4BR6e7KJ+7kzZpJAp6E91zENzflrj7aROg4tP4tFknCtxws3WNtuoZpQA==}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{secrets.ip-172-31-17-179.ec2.internal}}" > ~/.ssh/known_hosts

    - name: Transfer Files to EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{secrets.ip-172-31-17-179.ec2.internal}}
        username: ubuntu
        key: ${{secrets.MIIEpAIBAAKCAQEA/OVWq9L7uUe7M4WxH1J0/pxfCP7xILim5n7nLiZk3Ho/QMhzVeerAURtofGw/HRKL/2OSFgWUNRxuDZJg+FwyAGKZc+aU7UtPPENSs13wgCHLLFAk4c8Fs8xIDxHp4uzB6Bo+ySvOEYycWf5O6raWM5hPkAhG1V5okjEoHRiZE1lnNYcq4fieybJIKUA8YSKQPbTkBMxz7TkxfGSajCBz96hfTMPmK1RD2W4oX0AFkmMYzphGYV38MKRRN+mVTRrdpXYCxxJL1oxRYu/6KE4IoXXc46m5qwuJ4E7j2d+U7EXYROJ5ke+zBA0E2P27tSox4U6DJLiYNevavgus3Ka/QIDAQABAoIBADpqNwTlbSO0//a8sNcNUtzk/ca0LLpkLJkdQwUT9URAMJAkPQ/gvU1Doxc/HqSRr/k51j27qxvsln/4ei6uSkDIqlEuDPW86cAj5fAbWchEGvUl1Ea/fA/AuBY8FkkLKcVfNiCcrqSPAmPTomw34MuWkDuy0HLh4YCs0k5F09xa1svqqM3TzfaIKtYW8GCoHSnI7wgFpVjGwoQ3V8fQJ6iNZn/nXN0UCUIQxtFttp3AOBWZlKO6IAX88BdUkoM2x9QjST3J4QtxxRoj2SQzD9EKrKnRo9BMQMz/ktSDWcbG37JGQm6cWAxED8mwdXzTqRRNysfYrWrjmM8Ru48DlzkCgYEA/os8pMoRvdzecJiKv0qtWI8WMNuC/291ztqmi2W18B9feJbFvo216SGLYhTH4iuixR66uvAfg8woxyWWbt14tPoo4FfoljnO+T0yIEUUsOL+u7L9sH02wYg0fv3pQNuptwCkhrJJPNSeBR6yhpNsra3M7P8kInCatemcBOf/v8sCgYEA/lewL0GbjcyvNbDCt364HVXp0kbmfOEKGSZIBG1uGP/+psxI6TOJrmEES+RmPih/g32ylMnwbQWAfT1pC8XognO26dCTEECMMMMq7WUta4vJ2DN0fZD+5JF+dUUNTZDpMvfJ4Xe6EwUBwfOBUuj3Y3FFUjMV+qCR35YVdtzhp1cCgYEAhxqeQJUkX5L42eiNVEUtxuCDlcEdQbkGXZm+ZiTBMcdlJBtar+6FjE0Kry96fHhOt7O8xvYmtAzL5A/2Tbftlplk0ta2E+5xBedOUMR52/1P2Y6CioebZZOG0ZSxloRBC2oi6X990fTEPtFxTm63c2PZbj1qD4GXDFEHR69gFosCgYACXgqTxgaOoVMYKtcFIjbQfxY4ENTgYK/ZYBPXhrU5olhacRhUo1gquVhy5GNXPMVDEg5xeBe2zBBQGhw6MdNiM3WGY5ya0B797TMfFov/rkNoscHp0UmuEvScXtIq4KhrAwdsA9NFjgxgI8YWYXi8Ajfk9fjEZm41KI52lsO67QKBgQCpwkaF4tNB6fPkaVQuIVKZs4APo7eaJIsXue5MntU2rvDmiTXdG1tASBfy8EeL32/HvqnyzkDQUzedcG1aSRdc50oeffWl35guBU8Qhp+fWY+nRxpYg4BR6e7KJ+7kzZpJAp6E91zENzflrj7aROg4tP4tFknCtxws3WNtuoZpQA==}}
        source: "./app.R"
        target: "/home/ubuntu/app.R"

    - name: Restart Shiny Server
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << EOF
        sudo systemctl restart shiny-server
        EOF
