name: Deploy R Program to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy R Program to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure SSH Key
      run: |
        # Create .ssh directory
        mkdir -p /home/runner/.ssh
        
        # Add private key from GitHub Secrets
        echo "${{ secrets.EC2_SSH_KEY }}" > /home/runner/.ssh/id_rsa
        chmod 600 /home/runner/.ssh/id_rsa
        # Add EC2 instance to known hosts
        ssh-keyscan -H "54.164.80.110" >> /home/runner/.ssh/known_hosts

    - name: Copy R Script to EC2
      run: |
        scp -o StrictHostKeyChecking=no app.r ec2-user@54.164.80.110:/home/ec2-user/

    - name: Create Rlibs Directory and Install R Packages
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.164.80.110 "
          mkdir -p /home/ec2-user/Rlibs &&
          chmod 700 /home/ec2-user/Rlibs &&
          R -e 'install.packages(\"shiny\", lib=\"/home/ec2-user/Rlibs\", repos=\"https://cran.r-project.org\")'
        "

    - name: Execute R Script on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.164.80.110 "nohup Rscript /home/ec2-user/app.r &"

