name: Deploy and Execute R Script on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-and-execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Start SSH agent and add private key
      run: |
        eval $(ssh-agent -s)
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-add ~/.ssh/id_rsa

    - name: Copy R Script to EC2
      env:
        EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
        EC2_USER: ec2-user
        SCRIPT_PATH: ~/simple-r-app
      run: |
        scp -o StrictHostKeyChecking=no app.r ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:${{ env.SCRIPT_PATH }}

    - name: Execute R Script on EC2
      env:
        EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
        EC2_USER: ec2-user
        SCRIPT_PATH: ~/simple-r-app/app.r
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} "Rscript ${{ env.SCRIPT_PATH }}"
